# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 2
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Thank you for your contribution, we value it! However, this issue
  has been marked as stale because it has not had recent activity, or
  because it does not comply with our contribution guidelines. If it
  is the latter, please follow the instructions from the comment above
  to comply with our guidelines.
  It will be closed if no further activity occurs. Thank you for your
  contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: false

# Set to true to ignore issues with an assignee (defaults to false)
exemptAssignees: false

onlyLabels:
  - needs-context
