/**
 * ORY Oathkeeper
 * ORY Oathkeeper is a reverse proxy that checks the HTTP Authorization for validity against a set of rules. This service uses Hydra to validate access tokens and policies.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OryOathkeeper);
  }
}(this, function(expect, OryOathkeeper) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OryOathkeeper.Rule();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Rule', function() {
    it('should create an instance of Rule', function() {
      // uncomment below and update the code to test Rule
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be.a(OryOathkeeper.Rule);
    });

    it('should have the property authenticators (base name: "authenticators")', function() {
      // uncomment below and update the code to test the property authenticators
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be();
    });

    it('should have the property authorizer (base name: "authorizer")', function() {
      // uncomment below and update the code to test the property authorizer
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be();
    });

    it('should have the property credentialsIssuer (base name: "credentials_issuer")', function() {
      // uncomment below and update the code to test the property credentialsIssuer
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be();
    });

    it('should have the property match (base name: "match")', function() {
      // uncomment below and update the code to test the property match
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be();
    });

    it('should have the property upstream (base name: "upstream")', function() {
      // uncomment below and update the code to test the property upstream
      //var instane = new OryOathkeeper.Rule();
      //expect(instance).to.be();
    });

  });

}));
