includes:
  - from_url:
      url: https://raw.githubusercontent.com/ory/xgoreleaser/master/build.tmpl.yml

variables:
  brew_name: oathkeeper
  brew_description: "The Ory Identity and Access Proxy (Ory Oathkeeper)"
  buildinfo_hash: "github.com/ory/oathkeeper/x.Commit"
  buildinfo_tag: "github.com/ory/oathkeeper/x.Version"
  buildinfo_date: "github.com/ory/oathkeeper/x.Date"
  dockerfile: "./Dockerfile-alpine"

project_name: oathkeeper
