# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: oathkeeper

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go install github.com/gobuffalo/packr/v2/packr2
    - packr2

builds:
  -
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/ory/oathkeeper/x.Version={{.Tag}} -X github.com/ory/oathkeeper/x.Commit={{.FullCommit}} -X github.com/ory/oathkeeper/x.Date={{.Date}}
    binary: oathkeeper
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  -
    replacements:
      darwin: macOS
      386: 32-bit
      amd64: 64-bit
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

brews:
  -
    tap:
      owner: ory
      name: homebrew-oathkeeper
    homepage:  https://www.ory.sh
    goarm: 6
    commit_author:
      name: aeneasr
      email: aeneas@ory.sh

scoop:
  bucket:
    owner: ory
    name: scoop-oathkeeper
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: aeneas@ory.sh

dockers:
  - dockerfile: Dockerfile
    ids:
      - oathkeeper
    image_templates:
      - "oryd/oathkeeper:v{{ .Major }}"
      - "oryd/oathkeeper:v{{ .Major }}.{{ .Minor }}"
      - "oryd/oathkeeper:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "oryd/oathkeeper:{{ .Tag }}"
      - "oryd/oathkeeper:latest"
  - dockerfile: Dockerfile-alpine
    ids:
      - oathkeeper
    image_templates:
      - "oryd/oathkeeper:v{{ .Major }}-alpine"
      - "oryd/oathkeeper:v{{ .Major }}.{{ .Minor }}-alpine"
      - "oryd/oathkeeper:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-alpine"
      - "oryd/oathkeeper:{{ .Tag }}-alpine"
      - "oryd/oathkeeper:latest-alpine"

release:
  prerelease: auto
