# To compile this image manually run:
#
# $ make docker
FROM alpine:3.13

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin
RUN apk add -U --no-cache ca-certificates

COPY oathkeeper /usr/bin/oathkeeper

USER ory

ENTRYPOINT ["oathkeeper"]
CMD ["serve"]
