FROM golang:1.19 AS build

RUN apk --no-cache --update-cache --upgrade --latest add ca-certificates

ADD . /app
WORKDIR /app
ENV GO111MODULE on
RUN go mod download && go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

FROM gcr.io/distroless/static-debian11:debug
COPY --from=build /app/oathkeeper /app/oathkeeper

ENTRYPOINT ["/app/oathkeeper"]
CMD ["serve"]
