# To compile this image manually run:
#
# $ make docker
FROM alpine:3.15.4

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin
RUN apk --no-cache --update-cache --upgrade --latest add ca-certificates

COPY oathkeeper /usr/bin/oathkeeper

USER ory

ENTRYPOINT ["oathkeeper"]
CMD ["serve"]
