FROM golang:1.20-alpine3.18 AS builder

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin

RUN apk --no-cache --update-cache --upgrade --latest add ca-certificates

COPY . /app
WORKDIR /app
ENV GO111MODULE on
RUN go mod download && go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

############
FROM alpine:3.18 AS runner

RUN apk --no-cache --update-cache --upgrade --latest add ca-certificates

COPY --from=builder /app/oathkeeper /usr/bin/oathkeeper
USER 1000

EXPOSE 4455
EXPOSE 4456

ENTRYPOINT ["/usr/bin/oathkeeper"]
CMD ["serve"]
