FROM golang:1.16-alpine3.14

RUN addgroup -S ory; \
    adduser -S ory -G ory -D -H -s /bin/nologin

RUN apk add -U --no-cache ca-certificates

RUN go get -u github.com/gobuffalo/packr/v2/packr2
ADD . /app
WORKDIR /app
ENV GO111MODULE on
RUN go mod download
RUN packr2
RUN go mod download && go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

USER ory

ENTRYPOINT ["/app/oathkeeper"]
CMD ["serve"]
