// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/oathkeeper/internal/httpclient/models"
)

// DecisionsReader is a Reader for the Decisions structure.
type DecisionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DecisionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDecisionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDecisionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDecisionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDecisionsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDecisionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDecisionsOK creates a DecisionsOK with default headers values
func NewDecisionsOK() *DecisionsOK {
	return &DecisionsOK{}
}

/*DecisionsOK handles this case with default header values.

An empty response
*/
type DecisionsOK struct {
}

func (o *DecisionsOK) Error() string {
	return fmt.Sprintf("[GET /decisions][%d] decisionsOK ", 200)
}

func (o *DecisionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDecisionsUnauthorized creates a DecisionsUnauthorized with default headers values
func NewDecisionsUnauthorized() *DecisionsUnauthorized {
	return &DecisionsUnauthorized{}
}

/*DecisionsUnauthorized handles this case with default header values.

genericError
*/
type DecisionsUnauthorized struct {
	Payload *models.GenericError
}

func (o *DecisionsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /decisions][%d] decisionsUnauthorized  %+v", 401, o.Payload)
}

func (o *DecisionsUnauthorized) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DecisionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDecisionsForbidden creates a DecisionsForbidden with default headers values
func NewDecisionsForbidden() *DecisionsForbidden {
	return &DecisionsForbidden{}
}

/*DecisionsForbidden handles this case with default header values.

genericError
*/
type DecisionsForbidden struct {
	Payload *models.GenericError
}

func (o *DecisionsForbidden) Error() string {
	return fmt.Sprintf("[GET /decisions][%d] decisionsForbidden  %+v", 403, o.Payload)
}

func (o *DecisionsForbidden) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DecisionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDecisionsNotFound creates a DecisionsNotFound with default headers values
func NewDecisionsNotFound() *DecisionsNotFound {
	return &DecisionsNotFound{}
}

/*DecisionsNotFound handles this case with default header values.

genericError
*/
type DecisionsNotFound struct {
	Payload *models.GenericError
}

func (o *DecisionsNotFound) Error() string {
	return fmt.Sprintf("[GET /decisions][%d] decisionsNotFound  %+v", 404, o.Payload)
}

func (o *DecisionsNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DecisionsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDecisionsInternalServerError creates a DecisionsInternalServerError with default headers values
func NewDecisionsInternalServerError() *DecisionsInternalServerError {
	return &DecisionsInternalServerError{}
}

/*DecisionsInternalServerError handles this case with default header values.

genericError
*/
type DecisionsInternalServerError struct {
	Payload *models.GenericError
}

func (o *DecisionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /decisions][%d] decisionsInternalServerError  %+v", 500, o.Payload)
}

func (o *DecisionsInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DecisionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
