// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetWellKnownJSONWebKeysParams creates a new GetWellKnownJSONWebKeysParams object
// with the default values initialized.
func NewGetWellKnownJSONWebKeysParams() *GetWellKnownJSONWebKeysParams {

	return &GetWellKnownJSONWebKeysParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWellKnownJSONWebKeysParamsWithTimeout creates a new GetWellKnownJSONWebKeysParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWellKnownJSONWebKeysParamsWithTimeout(timeout time.Duration) *GetWellKnownJSONWebKeysParams {

	return &GetWellKnownJSONWebKeysParams{

		timeout: timeout,
	}
}

// NewGetWellKnownJSONWebKeysParamsWithContext creates a new GetWellKnownJSONWebKeysParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWellKnownJSONWebKeysParamsWithContext(ctx context.Context) *GetWellKnownJSONWebKeysParams {

	return &GetWellKnownJSONWebKeysParams{

		Context: ctx,
	}
}

// NewGetWellKnownJSONWebKeysParamsWithHTTPClient creates a new GetWellKnownJSONWebKeysParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWellKnownJSONWebKeysParamsWithHTTPClient(client *http.Client) *GetWellKnownJSONWebKeysParams {

	return &GetWellKnownJSONWebKeysParams{
		HTTPClient: client,
	}
}

/*GetWellKnownJSONWebKeysParams contains all the parameters to send to the API endpoint
for the get well known JSON web keys operation typically these are written to a http.Request
*/
type GetWellKnownJSONWebKeysParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get well known JSON web keys params
func (o *GetWellKnownJSONWebKeysParams) WithTimeout(timeout time.Duration) *GetWellKnownJSONWebKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get well known JSON web keys params
func (o *GetWellKnownJSONWebKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get well known JSON web keys params
func (o *GetWellKnownJSONWebKeysParams) WithContext(ctx context.Context) *GetWellKnownJSONWebKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get well known JSON web keys params
func (o *GetWellKnownJSONWebKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get well known JSON web keys params
func (o *GetWellKnownJSONWebKeysParams) WithHTTPClient(client *http.Client) *GetWellKnownJSONWebKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get well known JSON web keys params
func (o *GetWellKnownJSONWebKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWellKnownJSONWebKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
