// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/oathkeeper/internal/httpclient/models"
)

// ListRulesReader is a Reader for the ListRules structure.
type ListRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListRulesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListRulesOK creates a ListRulesOK with default headers values
func NewListRulesOK() *ListRulesOK {
	return &ListRulesOK{}
}

/*
ListRulesOK describes a response with status code 200, with default header values.

A list of rules
*/
type ListRulesOK struct {
	Payload []*models.Rule
}

// IsSuccess returns true when this list rules o k response has a 2xx status code
func (o *ListRulesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list rules o k response has a 3xx status code
func (o *ListRulesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list rules o k response has a 4xx status code
func (o *ListRulesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list rules o k response has a 5xx status code
func (o *ListRulesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list rules o k response a status code equal to that given
func (o *ListRulesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListRulesOK) Error() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesOK  %+v", 200, o.Payload)
}

func (o *ListRulesOK) String() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesOK  %+v", 200, o.Payload)
}

func (o *ListRulesOK) GetPayload() []*models.Rule {
	return o.Payload
}

func (o *ListRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRulesInternalServerError creates a ListRulesInternalServerError with default headers values
func NewListRulesInternalServerError() *ListRulesInternalServerError {
	return &ListRulesInternalServerError{}
}

/*
ListRulesInternalServerError describes a response with status code 500, with default header values.

genericError
*/
type ListRulesInternalServerError struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this list rules internal server error response has a 2xx status code
func (o *ListRulesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list rules internal server error response has a 3xx status code
func (o *ListRulesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list rules internal server error response has a 4xx status code
func (o *ListRulesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list rules internal server error response has a 5xx status code
func (o *ListRulesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list rules internal server error response a status code equal to that given
func (o *ListRulesInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *ListRulesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesInternalServerError  %+v", 500, o.Payload)
}

func (o *ListRulesInternalServerError) String() string {
	return fmt.Sprintf("[GET /rules][%d] listRulesInternalServerError  %+v", 500, o.Payload)
}

func (o *ListRulesInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *ListRulesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
