// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWellKnownParams creates a new GetWellKnownParams object
// with the default values initialized.
func NewGetWellKnownParams() *GetWellKnownParams {

	return &GetWellKnownParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWellKnownParamsWithTimeout creates a new GetWellKnownParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWellKnownParamsWithTimeout(timeout time.Duration) *GetWellKnownParams {

	return &GetWellKnownParams{

		timeout: timeout,
	}
}

// NewGetWellKnownParamsWithContext creates a new GetWellKnownParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWellKnownParamsWithContext(ctx context.Context) *GetWellKnownParams {

	return &GetWellKnownParams{

		Context: ctx,
	}
}

// NewGetWellKnownParamsWithHTTPClient creates a new GetWellKnownParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWellKnownParamsWithHTTPClient(client *http.Client) *GetWellKnownParams {

	return &GetWellKnownParams{
		HTTPClient: client,
	}
}

/*GetWellKnownParams contains all the parameters to send to the API endpoint
for the get well known operation typically these are written to a http.Request
*/
type GetWellKnownParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get well known params
func (o *GetWellKnownParams) WithTimeout(timeout time.Duration) *GetWellKnownParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get well known params
func (o *GetWellKnownParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get well known params
func (o *GetWellKnownParams) WithContext(ctx context.Context) *GetWellKnownParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get well known params
func (o *GetWellKnownParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get well known params
func (o *GetWellKnownParams) WithHTTPClient(client *http.Client) *GetWellKnownParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get well known params
func (o *GetWellKnownParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWellKnownParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
