// Code generated by go-swagger; DO NOT EDIT.

package judge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// JudgeReader is a Reader for the Judge structure.
type JudgeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JudgeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJudgeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewJudgeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewJudgeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewJudgeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewJudgeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJudgeOK creates a JudgeOK with default headers values
func NewJudgeOK() *JudgeOK {
	return &JudgeOK{}
}

/*JudgeOK handles this case with default header values.

An empty response
*/
type JudgeOK struct {
}

func (o *JudgeOK) Error() string {
	return fmt.Sprintf("[GET /judge][%d] judgeOK ", 200)
}

func (o *JudgeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewJudgeUnauthorized creates a JudgeUnauthorized with default headers values
func NewJudgeUnauthorized() *JudgeUnauthorized {
	return &JudgeUnauthorized{}
}

/*JudgeUnauthorized handles this case with default header values.

The standard error format
*/
type JudgeUnauthorized struct {
	Payload *JudgeUnauthorizedBody
}

func (o *JudgeUnauthorized) Error() string {
	return fmt.Sprintf("[GET /judge][%d] judgeUnauthorized  %+v", 401, o.Payload)
}

func (o *JudgeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(JudgeUnauthorizedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJudgeForbidden creates a JudgeForbidden with default headers values
func NewJudgeForbidden() *JudgeForbidden {
	return &JudgeForbidden{}
}

/*JudgeForbidden handles this case with default header values.

The standard error format
*/
type JudgeForbidden struct {
	Payload *JudgeForbiddenBody
}

func (o *JudgeForbidden) Error() string {
	return fmt.Sprintf("[GET /judge][%d] judgeForbidden  %+v", 403, o.Payload)
}

func (o *JudgeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(JudgeForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJudgeNotFound creates a JudgeNotFound with default headers values
func NewJudgeNotFound() *JudgeNotFound {
	return &JudgeNotFound{}
}

/*JudgeNotFound handles this case with default header values.

The standard error format
*/
type JudgeNotFound struct {
	Payload *JudgeNotFoundBody
}

func (o *JudgeNotFound) Error() string {
	return fmt.Sprintf("[GET /judge][%d] judgeNotFound  %+v", 404, o.Payload)
}

func (o *JudgeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(JudgeNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJudgeInternalServerError creates a JudgeInternalServerError with default headers values
func NewJudgeInternalServerError() *JudgeInternalServerError {
	return &JudgeInternalServerError{}
}

/*JudgeInternalServerError handles this case with default header values.

The standard error format
*/
type JudgeInternalServerError struct {
	Payload *JudgeInternalServerErrorBody
}

func (o *JudgeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /judge][%d] judgeInternalServerError  %+v", 500, o.Payload)
}

func (o *JudgeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(JudgeInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*JudgeForbiddenBody judge forbidden body
swagger:model JudgeForbiddenBody
*/
type JudgeForbiddenBody struct {

	// code
	Code int64 `json:"code,omitempty"`

	// details
	Details []map[string]interface{} `json:"details"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// request
	Request string `json:"request,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this judge forbidden body
func (o *JudgeForbiddenBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *JudgeForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *JudgeForbiddenBody) UnmarshalBinary(b []byte) error {
	var res JudgeForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*JudgeInternalServerErrorBody judge internal server error body
swagger:model JudgeInternalServerErrorBody
*/
type JudgeInternalServerErrorBody struct {

	// code
	Code int64 `json:"code,omitempty"`

	// details
	Details []map[string]interface{} `json:"details"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// request
	Request string `json:"request,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this judge internal server error body
func (o *JudgeInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *JudgeInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *JudgeInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res JudgeInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*JudgeNotFoundBody judge not found body
swagger:model JudgeNotFoundBody
*/
type JudgeNotFoundBody struct {

	// code
	Code int64 `json:"code,omitempty"`

	// details
	Details []map[string]interface{} `json:"details"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// request
	Request string `json:"request,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this judge not found body
func (o *JudgeNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *JudgeNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *JudgeNotFoundBody) UnmarshalBinary(b []byte) error {
	var res JudgeNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*JudgeUnauthorizedBody judge unauthorized body
swagger:model JudgeUnauthorizedBody
*/
type JudgeUnauthorizedBody struct {

	// code
	Code int64 `json:"code,omitempty"`

	// details
	Details []map[string]interface{} `json:"details"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`

	// request
	Request string `json:"request,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this judge unauthorized body
func (o *JudgeUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *JudgeUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *JudgeUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res JudgeUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
