sequenceDiagram
    participant UA as User Agent
    participant FW as ORY Oathkeeper
    participant OA2 as ORY Hydra
    participant API as API Endpoint

    UA->>FW: HTTP Request with opaque access token
    activate FW
    FW->>OA2: Ask for access request validation
    activate OA2
    OA2->>OA2: Process access request
    OA2->>FW: Forbid access request
    deactivate OA2
    FW->>UA: HTTP 403 Forbidden
    deactivate FW
