graph LR

    UA[User Agent] --- APIR[API Router]

    APIR ---  FW1[ORY Oathkeeper]
    subgraph Service 1
    FW1 --- API1[API Endpoint 1]
    end

    APIR ---  FW2[ORY Oathkeeper]
    subgraph Service 2
    FW2 --- API2[API Endpoint 2]
    end

    APIR ---  FW3[ORY Oathkeeper]
    subgraph Service 3
    FW3 --- API3[API Endpoint 3]
    end