sequenceDiagram
    participant UA as User Agent
    participant FW as ORY Oathkeeper
    participant OA2 as ORY Hydra
    participant API as API Endpoint

    UA->>FW: HTTP Request with opaque access token
    activate FW
    FW->>OA2: Ask for access request validation
    activate OA2
    OA2->>OA2: Process access request
    OA2->>FW: Approve request and return identity information
   deactivate OA2
    FW->>FW: Generate JWT ID Token
    FW->>API: Forward request with ID Token
    activate API
    API->>API: Process request with user info from ID token
    API->>FW: Return response
    deactivate API
    FW->>UA: Forward response
    deactivate FW
