// Copyright © 2026 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/rpctest/gen/go/ory/rpctest/rpctestconnect (interfaces: TestServiceHandler)
//
// Generated by this command:
//
//	mockgen -destination=connect_mock_server_test.go -package=middleware_test github.com/ory/rpctest/gen/go/ory/rpctest/rpctestconnect TestServiceHandler
//

// Package middleware_test is a generated GoMock package.
package middleware_test

import (
	context "context"
	reflect "reflect"

	connect "connectrpc.com/connect"
	gomock "go.uber.org/mock/gomock"

	rpctest "github.com/ory/rpctest/gen/go/ory/rpctest"
)

// MockTestServiceHandler is a mock of TestServiceHandler interface.
type MockTestServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockTestServiceHandlerMockRecorder
	isgomock struct{}
}

// MockTestServiceHandlerMockRecorder is the mock recorder for MockTestServiceHandler.
type MockTestServiceHandlerMockRecorder struct {
	mock *MockTestServiceHandler
}

// NewMockTestServiceHandler creates a new mock instance.
func NewMockTestServiceHandler(ctrl *gomock.Controller) *MockTestServiceHandler {
	mock := &MockTestServiceHandler{ctrl: ctrl}
	mock.recorder = &MockTestServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestServiceHandler) EXPECT() *MockTestServiceHandlerMockRecorder {
	return m.recorder
}

// BidiStream mocks base method.
func (m *MockTestServiceHandler) BidiStream(arg0 context.Context, arg1 *connect.BidiStream[rpctest.BidiStreamRequest, rpctest.BidiStreamResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BidiStream", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BidiStream indicates an expected call of BidiStream.
func (mr *MockTestServiceHandlerMockRecorder) BidiStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidiStream", reflect.TypeOf((*MockTestServiceHandler)(nil).BidiStream), arg0, arg1)
}

// ClientStream mocks base method.
func (m *MockTestServiceHandler) ClientStream(arg0 context.Context, arg1 *connect.ClientStream[rpctest.ClientStreamRequest]) (*connect.Response[rpctest.ClientStreamResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientStream", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[rpctest.ClientStreamResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientStream indicates an expected call of ClientStream.
func (mr *MockTestServiceHandlerMockRecorder) ClientStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStream", reflect.TypeOf((*MockTestServiceHandler)(nil).ClientStream), arg0, arg1)
}

// ServerStream mocks base method.
func (m *MockTestServiceHandler) ServerStream(arg0 context.Context, arg1 *connect.Request[rpctest.ServerStreamRequest], arg2 *connect.ServerStream[rpctest.ServerStreamResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerStream", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServerStream indicates an expected call of ServerStream.
func (mr *MockTestServiceHandlerMockRecorder) ServerStream(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStream", reflect.TypeOf((*MockTestServiceHandler)(nil).ServerStream), arg0, arg1, arg2)
}

// Unary mocks base method.
func (m *MockTestServiceHandler) Unary(arg0 context.Context, arg1 *connect.Request[rpctest.UnaryRequest]) (*connect.Response[rpctest.UnaryResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unary", arg0, arg1)
	ret0, _ := ret[0].(*connect.Response[rpctest.UnaryResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unary indicates an expected call of Unary.
func (mr *MockTestServiceHandlerMockRecorder) Unary(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unary", reflect.TypeOf((*MockTestServiceHandler)(nil).Unary), arg0, arg1)
}
