// Copyright © 2026 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/rpctest/gen/go/ory/rpctest (interfaces: TestServiceServer)
//
// Generated by this command:
//
//	mockgen -destination=grpc_mock_server_test.go -package=middleware_test github.com/ory/rpctest/gen/go/ory/rpctest TestServiceServer
//

// Package middleware_test is a generated GoMock package.
package middleware_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"

	rpctest "github.com/ory/rpctest/gen/go/ory/rpctest"
)

// MockTestServiceServer is a mock of TestServiceServer interface.
type MockTestServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestServiceServerMockRecorder
	isgomock struct{}
}

// MockTestServiceServerMockRecorder is the mock recorder for MockTestServiceServer.
type MockTestServiceServerMockRecorder struct {
	mock *MockTestServiceServer
}

// NewMockTestServiceServer creates a new mock instance.
func NewMockTestServiceServer(ctrl *gomock.Controller) *MockTestServiceServer {
	mock := &MockTestServiceServer{ctrl: ctrl}
	mock.recorder = &MockTestServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestServiceServer) EXPECT() *MockTestServiceServerMockRecorder {
	return m.recorder
}

// BidiStream mocks base method.
func (m *MockTestServiceServer) BidiStream(arg0 grpc.BidiStreamingServer[rpctest.BidiStreamRequest, rpctest.BidiStreamResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BidiStream", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BidiStream indicates an expected call of BidiStream.
func (mr *MockTestServiceServerMockRecorder) BidiStream(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidiStream", reflect.TypeOf((*MockTestServiceServer)(nil).BidiStream), arg0)
}

// ClientStream mocks base method.
func (m *MockTestServiceServer) ClientStream(arg0 grpc.ClientStreamingServer[rpctest.ClientStreamRequest, rpctest.ClientStreamResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientStream", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClientStream indicates an expected call of ClientStream.
func (mr *MockTestServiceServerMockRecorder) ClientStream(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStream", reflect.TypeOf((*MockTestServiceServer)(nil).ClientStream), arg0)
}

// ServerStream mocks base method.
func (m *MockTestServiceServer) ServerStream(arg0 *rpctest.ServerStreamRequest, arg1 grpc.ServerStreamingServer[rpctest.ServerStreamResponse]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerStream", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServerStream indicates an expected call of ServerStream.
func (mr *MockTestServiceServerMockRecorder) ServerStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStream", reflect.TypeOf((*MockTestServiceServer)(nil).ServerStream), arg0, arg1)
}

// Unary mocks base method.
func (m *MockTestServiceServer) Unary(arg0 context.Context, arg1 *rpctest.UnaryRequest) (*rpctest.UnaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unary", arg0, arg1)
	ret0, _ := ret[0].(*rpctest.UnaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unary indicates an expected call of Unary.
func (mr *MockTestServiceServerMockRecorder) Unary(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unary", reflect.TypeOf((*MockTestServiceServer)(nil).Unary), arg0, arg1)
}

// mustEmbedUnimplementedTestServiceServer mocks base method.
func (m *MockTestServiceServer) mustEmbedUnimplementedTestServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTestServiceServer")
}

// mustEmbedUnimplementedTestServiceServer indicates an expected call of mustEmbedUnimplementedTestServiceServer.
func (mr *MockTestServiceServerMockRecorder) mustEmbedUnimplementedTestServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTestServiceServer", reflect.TypeOf((*MockTestServiceServer)(nil).mustEmbedUnimplementedTestServiceServer))
}
