# Workaround for https://github.com/GoogleContainerTools/distroless/issues/1342
FROM golang:1.26-trixie AS builder

WORKDIR /go/src/github.com/ory/oathkeeper

RUN apt-get update && apt-get upgrade -y

COPY go.mod go.mod
COPY go.sum go.sum
COPY oryx/go.mod oryx/go.mod
COPY oryx/go.sum oryx/go.sum
COPY middleware/rpctest/go.mod middleware/rpctest/go.mod
COPY middleware/rpctest/go.sum middleware/rpctest/go.sum

ENV CGO_ENABLED=0

RUN go mod download

COPY . .

RUN go build -o /usr/bin/oathkeeper .

#########################

FROM gcr.io/distroless/static-debian12:nonroot AS runner

COPY --from=builder --chown=nonroot:nonroot /usr/bin/oathkeeper /usr/bin/oathkeeper

EXPOSE 4455 4456

ENTRYPOINT ["oathkeeper"]
CMD ["serve"]
