/*
 * Oathkeeper
 *
 * Oathkeeper
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SwaggerGetRuleParameters struct {

	// in: path
	Id string `json:"id"`
}
