/*
 * Oathkeeper
 *
 * Oathkeeper
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type SwaggerCreateRuleParameters struct {
	Body Rule `json:"Body,omitempty"`
}
