/**
 * ORY Oathkeeper
 * ORY Oathkeeper is a reverse proxy that checks the HTTP Authorization for validity against a set of rules. This service uses Hydra to validate access tokens and policies.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.OryOathkeeper) {
      root.OryOathkeeper = {};
    }
    root.OryOathkeeper.Upstream = factory(root.OryOathkeeper.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Upstream model module.
   * @module model/Upstream
   * @version Latest
   */

  /**
   * Constructs a new <code>Upstream</code>.
   * @alias module:model/Upstream
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Upstream</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Upstream} obj Optional instance to populate.
   * @return {module:model/Upstream} The populated <code>Upstream</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('preserve_host')) {
        obj['preserve_host'] = ApiClient.convertToType(data['preserve_host'], 'Boolean');
      }
      if (data.hasOwnProperty('strip_path')) {
        obj['strip_path'] = ApiClient.convertToType(data['strip_path'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * PreserveHost, if false (the default), tells ORY Oathkeeper to set the upstream request's Host header to the hostname of the API's upstream's URL. Setting this flag to true instructs ORY Oathkeeper not to do so.
   * @member {Boolean} preserve_host
   */
  exports.prototype['preserve_host'] = undefined;
  /**
   * StripPath if set, replaces the provided path prefix when forwarding the requested URL to the upstream URL.
   * @member {String} strip_path
   */
  exports.prototype['strip_path'] = undefined;
  /**
   * URL is the URL the request will be proxied to.
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


