// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// DecisionsReader DecisionsReader DecisionsReader is a Reader for the Decisions structure.
// swagger:model DecisionsReader
type DecisionsReader interface{}
