// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GetRuleReader GetRuleReader GetRuleReader is a Reader for the GetRule structure.
// swagger:model GetRuleReader
type GetRuleReader interface{}
