// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// GetWellKnownReader GetWellKnownReader GetWellKnownReader GetWellKnownReader GetWellKnownReader GetWellKnownReader GetWellKnownReader GetWellKnownReader is a Reader for the GetWellKnown structure.
// swagger:model GetWellKnownReader
type GetWellKnownReader interface{}
