// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// UpdateRuleReader UpdateRuleReader UpdateRuleReader UpdateRuleReader UpdateRuleReader UpdateRuleReader UpdateRuleReader UpdateRuleReader is a Reader for the UpdateRule structure.
// swagger:model UpdateRuleReader
type UpdateRuleReader interface{}
