name: Format

on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - id: cache-node
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npm ci --legacy-peer-deps
        if: steps.cache-node.outputs.cache-hit != 'true'
      - run: make format
      - name: Indicate formatting issues
        run: git diff HEAD --exit-code --color
